"""ABAP OOP Class Template"""

CLASS_TEMPLATE = """
CLASS {class_name} DEFINITION.
*"-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
*  Description: {description}
*  Author: Generated by ABAP AI Code Generator
*"-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  PUBLIC SECTION.
{public_methods}

  PRIVATE SECTION.
{private_methods}
{attributes}

ENDCLASS.

CLASS {class_name} IMPLEMENTATION.
{implementation}

ENDCLASS.
"""

BASIC_CLASS = """
CLASS z_calculator DEFINITION.

  PUBLIC SECTION.
    METHODS add
      IMPORTING p_num1 TYPE i
                p_num2 TYPE i
      RETURNING VALUE(result) TYPE i.
    
    METHODS subtract
      IMPORTING p_num1 TYPE i
                p_num2 TYPE i
      RETURNING VALUE(result) TYPE i.

ENDCLASS.

CLASS z_calculator IMPLEMENTATION.

  METHOD add.
    result = p_num1 + p_num2.
  ENDMETHOD.
  
  METHOD subtract.
    result = p_num1 - p_num2.
  ENDMETHOD.

ENDCLASS.
"""
