"""ABAP Function Module Template"""

FUNCTION_MODULE_TEMPLATE = """
FUNCTION {function_name}.
*"-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
*  Description: {description}
*  Author: Generated by ABAP AI Code Generator
*"-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

IMPORTING
{importing}
EXPORTING
{exporting}
TABLES
{tables}
CHANGING
{changing}
EXCEPTIONS
{exceptions}

  {logic}

ENDFUNCTION.
"""

BASIC_FUNCTION = """
FUNCTION z_add_numbers.
*"-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
*  Description: Simple function to add two numbers
*"-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

IMPORTING
  p_num1 TYPE i
  p_num2 TYPE i
EXPORTING
  p_result TYPE i

  p_result = p_num1 + p_num2.

ENDFUNCTION.
"""
