"""ABAP Report Template"""

REPORT_TEMPLATE = """
REPORT {report_name}.

* Description: {description}
* Author: Generated by ABAP AI Code Generator
* Date: {date}

{declarations}

START-OF-SELECTION.
  {logic}

END-OF-SELECTION.
  {output}
"""

BASIC_REPORT = """
REPORT z_my_report.

DATA: lt_data TYPE TABLE OF sflight,
      ls_data TYPE sflight.

START-OF-SELECTION.
  SELECT * FROM sflight INTO TABLE lt_data.
  
  IF sy-subrc = 0.
    LOOP AT lt_data INTO ls_data.
      WRITE: / ls_data-carrid, ls_data-connid, ls_data-fldate.
    ENDLOOP.
  ELSE.
    MESSAGE 'No data found' TYPE 'I'.
  ENDIF.

END-OF-SELECTION.
"""
